# Generated by Django 5.1.2 on 2024-10-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_id',
            new_name='Administrator_id',
        ),
    ]
