# Generated by Django 5.1.2 on 2024-10-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_rename_admin_administrator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrator',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Administrator_id',
            new_name='admin_id',
        ),
    ]
