# Generated by Django 5.1.2 on 2024-10-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_rename_administrator_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_id',
            new_name='Admin_id',
        ),
    ]
