# Generated by Django 5.1.2 on 2024-10-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0004_rename_admin_id_admin_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='admin',
        ),
        migrations.AlterField(
            model_name='warden',
            name='hostel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warden', to='hostel_management.hostel'),
        ),
    ]
