# Generated by Django 5.1.2 on 2024-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_remove_hostel_admin_alter_warden_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
